[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[[headers]]
  for = "/dist/*"
  [headers.values]
    "Cache-Control" = "dist, max-age=31536000, s-maxage=31536000"
